var array = [
    "Abu Dhabi",
    "Acre",
    "Afghanistan",
    "Ajman",
    "Alabama",
    "Alagoas",
    "&Aring;land Islands",
    "Alaska",
    "Albania",
    "Alberta",
    "Alderney",
    "Algeria",
    "Amapa",
    "Amazonas",
    "American Samoa",
    "Andalucia",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Aragon",
    "Argentina",
    "Arizona",
    "Arkansas",
    "Armenia",
    "Aruba",
    "Asturias",
    "Australia",
    "Australian Capital Territory",
    "Austria",
    "Azerbaijan",
    "Azores",
    "Baden-W&uuml;rttemberg",
    "Bahamas",
    "Bahia",
    "Bahrain",
    "Balearic Islands",
    "Bangladesh",
    "Barbados",
    "Basque",
    "Bavaria",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Berlin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire",
    "Bosnia and Herzegovina",
    "Bosniac-Croat Federation",
    "Botswana",
    "Brandenburg",
    "Brazil",
    "Bremen",
    "British Antarctic Territory",
    "British Columbia",
    "British Indian Ocean Territory",
    "British Virgin Islands",
    "Brittany",
    "Brunei",
    "Brussels",
    "Bulgaria",
    "Burgenland",
    "Burkina Faso",
    "Burundi",
    "California",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Canary Islands",
    "Cantabria",
    "Cape Verde",
    "Carinthia",
    "Castilla-La Mancha",
    "Castilla-Leon",
    "Catalonia",
    "Cayman Islands",
    "Cear&aacute;",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Chuuk",
    "Cocos Islands",
    "Colombia",
    "Colorado",
    "Comoros",
    "Connacht",
    "Connecticut",
    "Cornwall",
    "Corsica",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cura&ccedil;ao",
    "Cyprus",
    "Czech Republic",
    "Delaware",
    "Democratic Republic of the Congo",
    "Denmark",
    "Derbyshire",
    "Devon",
    "District of Columbia",
    "Djibouti",
    "Dominica",
    "Dominican Republi",
    "Dorset",
    "Drenthe",
    "Dubai",
    "East Anglia",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "England",
    "Equatorial Guinea",
    "Eritrea",
    "Espirito Santo",
    "Essex",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Extremadura",
    "Falkland Islands",
    "Faroe Islands",
    "Federal District",
    "Fiji",
    "Finland",
    "Flanders",
    "Flevoland",
    "Florida",
    "France",
    "French Guyana",
    "French Polynesia",
    "French Southern and Antarctic Lands",
    "Friesland",
    "Fujairah",
    "Gabon",
    "Galicia",
    "Gambia",
    "Gelderland",
    "Georgia (State)",
    "Georgia (Country)",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Gloucestershire",
    "Goi&aacute;s",
    "Greece",
    "Greenland",
    "Grenada",
    "Groningen",
    "Guadaloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea-Bissau",
    "Guinea",
    "Guyana",
    "Haiti",
    "Hamburg",
    "Hawaii",
    "Heard and McDonald Islands",
    "Hertfordshire",
    "Hesse",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "Idaho",
    "Illinois",
    "India",
    "Indiana",
    "Indonesia",
    "Iowa",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Isle of Wight",
    "Isles of Scilly",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kansas",
    "Karakalpakstan",
    "Kazakhstan",
    "Kent",
    "Kentucky",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kusiae",
    "Kuwait",
    "Kyrgyzstan",
    "La Rioja",
    "Lancashire",
    "Laos",
    "Latvia",
    "Lebanon",
    "Leinster",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Limburg",
    "Lincolnshire",
    "Lithuania",
    "Louisiana",
    "Lower Austria",
    "Lower Saxony",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Madeira",
    "Madrid",
    "Maine",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Manitoba",
    "Maranhao",
    "Marshall Islands",
    "Martinique",
    "Maryland",
    "Massachusetts",
    "Mato Grosso do Sul",
    "Mato Grosso",
    "Mauritania",
    "Mauritius",
    "Mecklenburg-Western Pomerania",
    "Mexico",
    "Michigan",
    "Micronesia",
    "Middlesex",
    "Midway Islands",
    "Minas Gerais",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montana",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "M&uuml;nster",
    "Murcia",
    "Namibia",
    "Nauru",
    "Navarre",
    "Nebraska",
    "Nepal",
    "Netherlands",
    "Nevada",
    "New Brunswick",
    "New Caledonia",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New South Wales",
    "New York",
    "Newfoundland and Labrador",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Noord-Brabant",
    "Noord-Holland",
    "Norfolk Islands",
    "North Carolina",
    "North Dakota",
    "North Korea",
    "North Macedonia",
    "North Rhine-Westphalia",
    "Northern Ireland",
    "Northern Territory",
    "Northumberland",
    "Northwest Territories",
    "Norway",
    "Nova Scotia",
    "Nunavut",
    "Ohio",
    "Oklahoma",
    "Oman",
    "Ontario",
    "Oregon",
    "Orkney Islands",
    "Overijssel",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Para",
    "Paraguay",
    "Paraiba",
    "Parana",
    "Pembrokeshire",
    "Peru",
    "Philippines",
    "Piaui",
    "Pitcairn Islands",
    "Pohnpei",
    "Poland",
    "Portugal",
    "Prince Edward Island",
    "Qatar",
    "Quebec",
    "Queensland",
    "Rass al Khaimah",
    "Republic of Congo",
    "Republika Srpska",
    "R&eacute;union",
    "Rhineland-Palatinate",
    "Rhode Island",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Romania",
    "Rondonia",
    "Roraima",
    "Russia",
    "Rwanda",
    "Saarland",
    "Saba",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Salzburg",
    "Samoa",
    "San Marino",
    "Santa Catarina",
    "S&atilde;o Paulo",
    "S&atilde;o Tom&eacute; and Principe",
    "Sark",
    "Saskatchewan",
    "Saudi Arabia",
    "Saxony-Anhalt",
    "Saxony",
    "Schleswig-Holstein",
    "Scotland",
    "Seborga",
    "Senegal",
    "Serbia",
    "Sergipe",
    "Seychelles",
    "Sharjah",
    "Shetland Islands",
    "Sierra Leone",
    "Singapore",
    "Sint Eustatius",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "Somaliland",
    "South Africa",
    "South Australia",
    "South Carolina",
    "South Dakota",
    "South Georgia and the South Sandwich Islands",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Styria",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Tasmania",
    "Tennessee",
    "Texas",
    "Thailand",
    "Thuringia",
    "Tibet",
    "Tocantins",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tristan ta Cunha",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Tyrol",
    "Uganda",
    "Ukraine",
    "Ulster",
    "Umm al Qaiwan",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "United States Virgin Islands",
    "Upper Austria",
    "Utah",
    "Utrecht",
    "Uzbekistan",
    "Valencia",
    "Vanuatu",
    "Vatican",
    "Venezuela",
    "Vermont",
    "Victoria",
    "Vienna",
    "Vietnam",
    "Virginia",
    "Vojvodina",
    "Vorarlberg",
    "Wake Island",
    "Wales",
    "Wallis and Futuna",
    "Walloon",
    "Washington",
    "West Virginia",
    "Western Australia",
    "Western Sahara",
    "Wisconsin",
    "Wyoming",
    "Yap",
    "Yorkshire",
    "Yukon",
    "Zambia",
    "Zeeland",
    "Zimbabwe",
    "Zuid Holland",
    "",
    "",
    "",
    "",
    "",
    ""
]

function autocomplete(inp, arr){
    var currentFocus;
    inp.addEventListener("input", function(e) {
        var a, b, i, val = this.value;
        closeAllLists();
        if (!val) {
            return false;
        }
        currentFocus = -1;
        a = document.createElement("DIV");
        a.setAttribute("id", this.id + "autocomplete-list");
        a.setAttribute("class", "autocomplete-items");
        this.parentNode.appendChild(a);
        for (i = 0; i < arr.length; i++) {
            if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
                b = document.createElement("DIV");
                b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
                b.innerHTML += arr[i].substr(val.length);
                b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
                b.addEventListener("click", function(e){
                    inp.value = this.getElementsByTagName("input")[0].value;
                })
            }
        }
    })
}